/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.loldictionarykmp.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param camille 
 */
@Serializable

data class CamilleChampionDetailObj (

    @SerialName(value = "Camille") @Required val camille: ChampionDetailObj

)

