/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.loldictionarykmp.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param aatrox 
 * @param ahri 
 * @param akali 
 * @param akshan 
 * @param alistar 
 * @param amumu 
 * @param anivia 
 * @param annie 
 * @param aphelios 
 * @param ashe 
 * @param aurelionSol 
 * @param azir 
 * @param bard 
 * @param belveth 
 * @param blitzcrank 
 * @param brand 
 * @param braum 
 * @param briar 
 * @param caitlyn 
 * @param camille 
 * @param cassiopeia 
 * @param chogath 
 * @param corki 
 * @param darius 
 * @param diana 
 * @param draven 
 * @param drMundo 
 * @param ekko 
 * @param elise 
 * @param evelynn 
 * @param ezreal 
 * @param fiddlesticks 
 * @param fiora 
 * @param fizz 
 * @param galio 
 * @param gangplank 
 * @param garen 
 * @param gnar 
 * @param gragas 
 * @param graves 
 * @param gwen 
 * @param hecarim 
 * @param heimerdinger 
 * @param illaoi 
 * @param irelia 
 * @param ivern 
 * @param janna 
 * @param jarvanIV 
 * @param jax 
 * @param jayce 
 * @param jhin 
 * @param jinx 
 * @param kaisa 
 * @param kalista 
 * @param karma 
 * @param karthus 
 * @param kassadin 
 * @param katarina 
 * @param kayle 
 * @param kayn 
 * @param kennen 
 * @param khazix 
 * @param kindred 
 * @param kled 
 * @param kogMaw 
 * @param ksante 
 * @param leblanc 
 * @param leeSin 
 * @param leona 
 * @param lillia 
 * @param lissandra 
 * @param lucian 
 * @param lulu 
 * @param lux 
 * @param malphite 
 * @param malzahar 
 * @param maokai 
 * @param masterYi 
 * @param milio 
 * @param missFortune 
 * @param monkeyKing 
 * @param mordekaiser 
 * @param morgana 
 * @param naafiri 
 * @param nami 
 * @param nasus 
 * @param nautilus 
 * @param neeko 
 * @param nidalee 
 * @param nilah 
 * @param nocturne 
 * @param nunu 
 * @param olaf 
 * @param orianna 
 * @param ornn 
 * @param pantheon 
 * @param poppy 
 * @param pyke 
 * @param qiyana 
 * @param quinn 
 * @param rakan 
 * @param rammus 
 * @param rekSai 
 * @param rell 
 * @param renata 
 * @param renekton 
 * @param rengar 
 * @param riven 
 * @param rumble 
 * @param ryze 
 * @param samira 
 * @param sejuani 
 * @param senna 
 * @param seraphine 
 * @param sett 
 * @param shaco 
 * @param shen 
 * @param shyvana 
 * @param singed 
 * @param sion 
 * @param sivir 
 * @param skarner 
 * @param sona 
 * @param soraka 
 * @param swain 
 * @param sylas 
 * @param syndra 
 * @param tahmKench 
 * @param taliyah 
 * @param talon 
 * @param taric 
 * @param teemo 
 * @param thresh 
 * @param tristana 
 * @param trundle 
 * @param tryndamere 
 * @param twistedFate 
 * @param twitch 
 * @param udyr 
 * @param urgot 
 * @param varus 
 * @param vayne 
 * @param veigar 
 * @param velkoz 
 * @param vex 
 * @param vi 
 * @param viego 
 * @param viktor 
 * @param vladimir 
 * @param volibear 
 * @param warwick 
 * @param xayah 
 * @param xerath 
 * @param xinZhao 
 * @param yasuo 
 * @param yone 
 * @param yorick 
 * @param yuumi 
 * @param zac 
 * @param zed 
 * @param zeri 
 * @param ziggs 
 * @param zilean 
 * @param zoe 
 * @param zyra 
 */
@Serializable

data class ChampionDetailDataData (

    @SerialName(value = "Aatrox") @Required val aatrox: ChampionDetailObj,

    @SerialName(value = "Ahri") @Required val ahri: ChampionDetailObj,

    @SerialName(value = "Akali") @Required val akali: ChampionDetailObj,

    @SerialName(value = "Akshan") @Required val akshan: ChampionDetailObj,

    @SerialName(value = "Alistar") @Required val alistar: ChampionDetailObj,

    @SerialName(value = "Amumu") @Required val amumu: ChampionDetailObj,

    @SerialName(value = "Anivia") @Required val anivia: ChampionDetailObj,

    @SerialName(value = "Annie") @Required val annie: ChampionDetailObj,

    @SerialName(value = "Aphelios") @Required val aphelios: ChampionDetailObj,

    @SerialName(value = "Ashe") @Required val ashe: ChampionDetailObj,

    @SerialName(value = "AurelionSol") @Required val aurelionSol: ChampionDetailObj,

    @SerialName(value = "Azir") @Required val azir: ChampionDetailObj,

    @SerialName(value = "Bard") @Required val bard: ChampionDetailObj,

    @SerialName(value = "Belveth") @Required val belveth: ChampionDetailObj,

    @SerialName(value = "Blitzcrank") @Required val blitzcrank: ChampionDetailObj,

    @SerialName(value = "Brand") @Required val brand: ChampionDetailObj,

    @SerialName(value = "Braum") @Required val braum: ChampionDetailObj,

    @SerialName(value = "Briar") @Required val briar: ChampionDetailObj,

    @SerialName(value = "Caitlyn") @Required val caitlyn: ChampionDetailObj,

    @SerialName(value = "Camille") @Required val camille: ChampionDetailObj,

    @SerialName(value = "Cassiopeia") @Required val cassiopeia: ChampionDetailObj,

    @SerialName(value = "Chogath") @Required val chogath: ChampionDetailObj,

    @SerialName(value = "Corki") @Required val corki: ChampionDetailObj,

    @SerialName(value = "Darius") @Required val darius: ChampionDetailObj,

    @SerialName(value = "Diana") @Required val diana: ChampionDetailObj,

    @SerialName(value = "Draven") @Required val draven: ChampionDetailObj,

    @SerialName(value = "DrMundo") @Required val drMundo: ChampionDetailObj,

    @SerialName(value = "Ekko") @Required val ekko: ChampionDetailObj,

    @SerialName(value = "Elise") @Required val elise: ChampionDetailObj,

    @SerialName(value = "Evelynn") @Required val evelynn: ChampionDetailObj,

    @SerialName(value = "Ezreal") @Required val ezreal: ChampionDetailObj,

    @SerialName(value = "Fiddlesticks") @Required val fiddlesticks: ChampionDetailObj,

    @SerialName(value = "Fiora") @Required val fiora: ChampionDetailObj,

    @SerialName(value = "Fizz") @Required val fizz: ChampionDetailObj,

    @SerialName(value = "Galio") @Required val galio: ChampionDetailObj,

    @SerialName(value = "Gangplank") @Required val gangplank: ChampionDetailObj,

    @SerialName(value = "Garen") @Required val garen: ChampionDetailObj,

    @SerialName(value = "Gnar") @Required val gnar: ChampionDetailObj,

    @SerialName(value = "Gragas") @Required val gragas: ChampionDetailObj,

    @SerialName(value = "Graves") @Required val graves: ChampionDetailObj,

    @SerialName(value = "Gwen") @Required val gwen: ChampionDetailObj,

    @SerialName(value = "Hecarim") @Required val hecarim: ChampionDetailObj,

    @SerialName(value = "Heimerdinger") @Required val heimerdinger: ChampionDetailObj,

    @SerialName(value = "Illaoi") @Required val illaoi: ChampionDetailObj,

    @SerialName(value = "Irelia") @Required val irelia: ChampionDetailObj,

    @SerialName(value = "Ivern") @Required val ivern: ChampionDetailObj,

    @SerialName(value = "Janna") @Required val janna: ChampionDetailObj,

    @SerialName(value = "JarvanIV") @Required val jarvanIV: ChampionDetailObj,

    @SerialName(value = "Jax") @Required val jax: ChampionDetailObj,

    @SerialName(value = "Jayce") @Required val jayce: ChampionDetailObj,

    @SerialName(value = "Jhin") @Required val jhin: ChampionDetailObj,

    @SerialName(value = "Jinx") @Required val jinx: ChampionDetailObj,

    @SerialName(value = "Kaisa") @Required val kaisa: ChampionDetailObj,

    @SerialName(value = "Kalista") @Required val kalista: ChampionDetailObj,

    @SerialName(value = "Karma") @Required val karma: ChampionDetailObj,

    @SerialName(value = "Karthus") @Required val karthus: ChampionDetailObj,

    @SerialName(value = "Kassadin") @Required val kassadin: ChampionDetailObj,

    @SerialName(value = "Katarina") @Required val katarina: ChampionDetailObj,

    @SerialName(value = "Kayle") @Required val kayle: ChampionDetailObj,

    @SerialName(value = "Kayn") @Required val kayn: ChampionDetailObj,

    @SerialName(value = "Kennen") @Required val kennen: ChampionDetailObj,

    @SerialName(value = "Khazix") @Required val khazix: ChampionDetailObj,

    @SerialName(value = "Kindred") @Required val kindred: ChampionDetailObj,

    @SerialName(value = "Kled") @Required val kled: ChampionDetailObj,

    @SerialName(value = "KogMaw") @Required val kogMaw: ChampionDetailObj,

    @SerialName(value = "KSante") @Required val ksante: ChampionDetailObj,

    @SerialName(value = "Leblanc") @Required val leblanc: ChampionDetailObj,

    @SerialName(value = "LeeSin") @Required val leeSin: ChampionDetailObj,

    @SerialName(value = "Leona") @Required val leona: ChampionDetailObj,

    @SerialName(value = "Lillia") @Required val lillia: ChampionDetailObj,

    @SerialName(value = "Lissandra") @Required val lissandra: ChampionDetailObj,

    @SerialName(value = "Lucian") @Required val lucian: ChampionDetailObj,

    @SerialName(value = "Lulu") @Required val lulu: ChampionDetailObj,

    @SerialName(value = "Lux") @Required val lux: ChampionDetailObj,

    @SerialName(value = "Malphite") @Required val malphite: ChampionDetailObj,

    @SerialName(value = "Malzahar") @Required val malzahar: ChampionDetailObj,

    @SerialName(value = "Maokai") @Required val maokai: ChampionDetailObj,

    @SerialName(value = "MasterYi") @Required val masterYi: ChampionDetailObj,

    @SerialName(value = "Milio") @Required val milio: ChampionDetailObj,

    @SerialName(value = "MissFortune") @Required val missFortune: ChampionDetailObj,

    @SerialName(value = "MonkeyKing") @Required val monkeyKing: ChampionDetailObj,

    @SerialName(value = "Mordekaiser") @Required val mordekaiser: ChampionDetailObj,

    @SerialName(value = "Morgana") @Required val morgana: ChampionDetailObj,

    @SerialName(value = "Naafiri") @Required val naafiri: ChampionDetailObj,

    @SerialName(value = "Nami") @Required val nami: ChampionDetailObj,

    @SerialName(value = "Nasus") @Required val nasus: ChampionDetailObj,

    @SerialName(value = "Nautilus") @Required val nautilus: ChampionDetailObj,

    @SerialName(value = "Neeko") @Required val neeko: ChampionDetailObj,

    @SerialName(value = "Nidalee") @Required val nidalee: ChampionDetailObj,

    @SerialName(value = "Nilah") @Required val nilah: ChampionDetailObj,

    @SerialName(value = "Nocturne") @Required val nocturne: ChampionDetailObj,

    @SerialName(value = "Nunu") @Required val nunu: ChampionDetailObj,

    @SerialName(value = "Olaf") @Required val olaf: ChampionDetailObj,

    @SerialName(value = "Orianna") @Required val orianna: ChampionDetailObj,

    @SerialName(value = "Ornn") @Required val ornn: ChampionDetailObj,

    @SerialName(value = "Pantheon") @Required val pantheon: ChampionDetailObj,

    @SerialName(value = "Poppy") @Required val poppy: ChampionDetailObj,

    @SerialName(value = "Pyke") @Required val pyke: ChampionDetailObj,

    @SerialName(value = "Qiyana") @Required val qiyana: ChampionDetailObj,

    @SerialName(value = "Quinn") @Required val quinn: ChampionDetailObj,

    @SerialName(value = "Rakan") @Required val rakan: ChampionDetailObj,

    @SerialName(value = "Rammus") @Required val rammus: ChampionDetailObj,

    @SerialName(value = "RekSai") @Required val rekSai: ChampionDetailObj,

    @SerialName(value = "Rell") @Required val rell: ChampionDetailObj,

    @SerialName(value = "Renata") @Required val renata: ChampionDetailObj,

    @SerialName(value = "Renekton") @Required val renekton: ChampionDetailObj,

    @SerialName(value = "Rengar") @Required val rengar: ChampionDetailObj,

    @SerialName(value = "Riven") @Required val riven: ChampionDetailObj,

    @SerialName(value = "Rumble") @Required val rumble: ChampionDetailObj,

    @SerialName(value = "Ryze") @Required val ryze: ChampionDetailObj,

    @SerialName(value = "Samira") @Required val samira: ChampionDetailObj,

    @SerialName(value = "Sejuani") @Required val sejuani: ChampionDetailObj,

    @SerialName(value = "Senna") @Required val senna: ChampionDetailObj,

    @SerialName(value = "Seraphine") @Required val seraphine: ChampionDetailObj,

    @SerialName(value = "Sett") @Required val sett: ChampionDetailObj,

    @SerialName(value = "Shaco") @Required val shaco: ChampionDetailObj,

    @SerialName(value = "Shen") @Required val shen: ChampionDetailObj,

    @SerialName(value = "Shyvana") @Required val shyvana: ChampionDetailObj,

    @SerialName(value = "Singed") @Required val singed: ChampionDetailObj,

    @SerialName(value = "Sion") @Required val sion: ChampionDetailObj,

    @SerialName(value = "Sivir") @Required val sivir: ChampionDetailObj,

    @SerialName(value = "Skarner") @Required val skarner: ChampionDetailObj,

    @SerialName(value = "Sona") @Required val sona: ChampionDetailObj,

    @SerialName(value = "Soraka") @Required val soraka: ChampionDetailObj,

    @SerialName(value = "Swain") @Required val swain: ChampionDetailObj,

    @SerialName(value = "Sylas") @Required val sylas: ChampionDetailObj,

    @SerialName(value = "Syndra") @Required val syndra: ChampionDetailObj,

    @SerialName(value = "TahmKench") @Required val tahmKench: ChampionDetailObj,

    @SerialName(value = "Taliyah") @Required val taliyah: ChampionDetailObj,

    @SerialName(value = "Talon") @Required val talon: ChampionDetailObj,

    @SerialName(value = "Taric") @Required val taric: ChampionDetailObj,

    @SerialName(value = "Teemo") @Required val teemo: ChampionDetailObj,

    @SerialName(value = "Thresh") @Required val thresh: ChampionDetailObj,

    @SerialName(value = "Tristana") @Required val tristana: ChampionDetailObj,

    @SerialName(value = "Trundle") @Required val trundle: ChampionDetailObj,

    @SerialName(value = "Tryndamere") @Required val tryndamere: ChampionDetailObj,

    @SerialName(value = "TwistedFate") @Required val twistedFate: ChampionDetailObj,

    @SerialName(value = "Twitch") @Required val twitch: ChampionDetailObj,

    @SerialName(value = "Udyr") @Required val udyr: ChampionDetailObj,

    @SerialName(value = "Urgot") @Required val urgot: ChampionDetailObj,

    @SerialName(value = "Varus") @Required val varus: ChampionDetailObj,

    @SerialName(value = "Vayne") @Required val vayne: ChampionDetailObj,

    @SerialName(value = "Veigar") @Required val veigar: ChampionDetailObj,

    @SerialName(value = "Velkoz") @Required val velkoz: ChampionDetailObj,

    @SerialName(value = "Vex") @Required val vex: ChampionDetailObj,

    @SerialName(value = "Vi") @Required val vi: ChampionDetailObj,

    @SerialName(value = "Viego") @Required val viego: ChampionDetailObj,

    @SerialName(value = "Viktor") @Required val viktor: ChampionDetailObj,

    @SerialName(value = "Vladimir") @Required val vladimir: ChampionDetailObj,

    @SerialName(value = "Volibear") @Required val volibear: ChampionDetailObj,

    @SerialName(value = "Warwick") @Required val warwick: ChampionDetailObj,

    @SerialName(value = "Xayah") @Required val xayah: ChampionDetailObj,

    @SerialName(value = "Xerath") @Required val xerath: ChampionDetailObj,

    @SerialName(value = "XinZhao") @Required val xinZhao: ChampionDetailObj,

    @SerialName(value = "Yasuo") @Required val yasuo: ChampionDetailObj,

    @SerialName(value = "Yone") @Required val yone: ChampionDetailObj,

    @SerialName(value = "Yorick") @Required val yorick: ChampionDetailObj,

    @SerialName(value = "Yuumi") @Required val yuumi: ChampionDetailObj,

    @SerialName(value = "Zac") @Required val zac: ChampionDetailObj,

    @SerialName(value = "Zed") @Required val zed: ChampionDetailObj,

    @SerialName(value = "Zeri") @Required val zeri: ChampionDetailObj,

    @SerialName(value = "Ziggs") @Required val ziggs: ChampionDetailObj,

    @SerialName(value = "Zilean") @Required val zilean: ChampionDetailObj,

    @SerialName(value = "Zoe") @Required val zoe: ChampionDetailObj,

    @SerialName(value = "Zyra") @Required val zyra: ChampionDetailObj

)

