/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.loldictionarykmp.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param id 
 * @param name 
 * @param description 
 * @param tooltip 
 * @param leveltip 
 * @param maxrank 
 * @param cooldown 
 * @param cooldownBurn 
 * @param cost 
 * @param costBurn 
 * @param costType 
 * @param maxammo 
 * @param range 
 * @param rangeBurn 
 * @param image 
 * @param resource 
 */
@Serializable

data class ChampionDetailObjSpellsInner (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "tooltip") val tooltip: kotlin.String? = null,

    @SerialName(value = "leveltip") val leveltip: LevelTipObj? = null,

    @SerialName(value = "maxrank") val maxrank: kotlin.Double? = null,

    @SerialName(value = "cooldown") val cooldown: kotlin.collections.List<kotlin.Double>? = null,

    @SerialName(value = "cooldownBurn") val cooldownBurn: kotlin.String? = null,

    @SerialName(value = "cost") val cost: kotlin.collections.List<kotlin.Double>? = null,

    @SerialName(value = "costBurn") val costBurn: kotlin.String? = null,

    @SerialName(value = "costType") val costType: kotlin.String? = null,

    @SerialName(value = "maxammo") val maxammo: kotlin.String? = null,

    @SerialName(value = "range") val range: kotlin.collections.List<kotlin.Double>? = null,

    @SerialName(value = "rangeBurn") val rangeBurn: kotlin.String? = null,

    @SerialName(value = "image") val image: ImageObj? = null,

    @SerialName(value = "resource") val resource: kotlin.String? = null

)

