/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.loldictionarykmp.models


import kotlinx.serialization.*

/**
 * 
 *
 * @param id 
 * @param num 
 * @param name 
 * @param chromas 
 */
@Serializable

data class ChampionDetailObjSkinsInner (

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "num") val num: kotlin.Double? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "chromas") val chromas: kotlin.Boolean? = null

)

