/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.loldictionarykmp.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param aatrox 
 * @param ahri 
 * @param akali 
 * @param akshan 
 * @param alistar 
 * @param amumu 
 * @param anivia 
 * @param annie 
 * @param aphelios 
 * @param ashe 
 * @param aurelionSol 
 * @param azir 
 * @param bard 
 * @param belveth 
 * @param blitzcrank 
 * @param brand 
 * @param braum 
 * @param briar 
 * @param caitlyn 
 * @param camille 
 * @param cassiopeia 
 * @param chogath 
 * @param corki 
 * @param darius 
 * @param diana 
 * @param draven 
 * @param drMundo 
 * @param ekko 
 * @param elise 
 * @param evelynn 
 * @param ezreal 
 * @param fiddlesticks 
 * @param fiora 
 * @param fizz 
 * @param galio 
 * @param gangplank 
 * @param garen 
 * @param gnar 
 * @param gragas 
 * @param graves 
 * @param gwen 
 * @param hecarim 
 * @param heimerdinger 
 * @param illaoi 
 * @param irelia 
 * @param ivern 
 * @param janna 
 * @param jarvanIV 
 * @param jax 
 * @param jayce 
 * @param jhin 
 * @param jinx 
 * @param kaisa 
 * @param kalista 
 * @param karma 
 * @param karthus 
 * @param kassadin 
 * @param katarina 
 * @param kayle 
 * @param kayn 
 * @param kennen 
 * @param khazix 
 * @param kindred 
 * @param kled 
 * @param kogMaw 
 * @param ksante 
 * @param leblanc 
 * @param leeSin 
 * @param leona 
 * @param lillia 
 * @param lissandra 
 * @param lucian 
 * @param lulu 
 * @param lux 
 * @param malphite 
 * @param malzahar 
 * @param maokai 
 * @param masterYi 
 * @param milio 
 * @param missFortune 
 * @param monkeyKing 
 * @param mordekaiser 
 * @param morgana 
 * @param naafiri 
 * @param nami 
 * @param nasus 
 * @param nautilus 
 * @param neeko 
 * @param nidalee 
 * @param nilah 
 * @param nocturne 
 * @param nunu 
 * @param olaf 
 * @param orianna 
 * @param ornn 
 * @param pantheon 
 * @param poppy 
 * @param pyke 
 * @param qiyana 
 * @param quinn 
 * @param rakan 
 * @param rammus 
 * @param rekSai 
 * @param rell 
 * @param renata 
 * @param renekton 
 * @param rengar 
 * @param riven 
 * @param rumble 
 * @param ryze 
 * @param samira 
 * @param sejuani 
 * @param senna 
 * @param seraphine 
 * @param sett 
 * @param shaco 
 * @param shen 
 * @param shyvana 
 * @param singed 
 * @param sion 
 * @param sivir 
 * @param skarner 
 * @param sona 
 * @param soraka 
 * @param swain 
 * @param sylas 
 * @param syndra 
 * @param tahmKench 
 * @param taliyah 
 * @param talon 
 * @param taric 
 * @param teemo 
 * @param thresh 
 * @param tristana 
 * @param trundle 
 * @param tryndamere 
 * @param twistedFate 
 * @param twitch 
 * @param udyr 
 * @param urgot 
 * @param varus 
 * @param vayne 
 * @param veigar 
 * @param velkoz 
 * @param vex 
 * @param vi 
 * @param viego 
 * @param viktor 
 * @param vladimir 
 * @param volibear 
 * @param warwick 
 * @param xayah 
 * @param xerath 
 * @param xinZhao 
 * @param yasuo 
 * @param yone 
 * @param yorick 
 * @param yuumi 
 * @param zac 
 * @param zed 
 * @param zeri 
 * @param ziggs 
 * @param zilean 
 * @param zoe 
 * @param zyra 
 */
@Serializable

data class ChampionsList (

    @SerialName(value = "Aatrox") @Required val aatrox: ChampionObj,

    @SerialName(value = "Ahri") @Required val ahri: ChampionObj,

    @SerialName(value = "Akali") @Required val akali: ChampionObj,

    @SerialName(value = "Akshan") @Required val akshan: ChampionObj,

    @SerialName(value = "Alistar") @Required val alistar: ChampionObj,

    @SerialName(value = "Amumu") @Required val amumu: ChampionObj,

    @SerialName(value = "Anivia") @Required val anivia: ChampionObj,

    @SerialName(value = "Annie") @Required val annie: ChampionObj,

    @SerialName(value = "Aphelios") @Required val aphelios: ChampionObj,

    @SerialName(value = "Ashe") @Required val ashe: ChampionObj,

    @SerialName(value = "AurelionSol") @Required val aurelionSol: ChampionObj,

    @SerialName(value = "Azir") @Required val azir: ChampionObj,

    @SerialName(value = "Bard") @Required val bard: ChampionObj,

    @SerialName(value = "Belveth") @Required val belveth: ChampionObj,

    @SerialName(value = "Blitzcrank") @Required val blitzcrank: ChampionObj,

    @SerialName(value = "Brand") @Required val brand: ChampionObj,

    @SerialName(value = "Braum") @Required val braum: ChampionObj,

    @SerialName(value = "Briar") @Required val briar: ChampionObj,

    @SerialName(value = "Caitlyn") @Required val caitlyn: ChampionObj,

    @SerialName(value = "Camille") @Required val camille: ChampionObj,

    @SerialName(value = "Cassiopeia") @Required val cassiopeia: ChampionObj,

    @SerialName(value = "Chogath") @Required val chogath: ChampionObj,

    @SerialName(value = "Corki") @Required val corki: ChampionObj,

    @SerialName(value = "Darius") @Required val darius: ChampionObj,

    @SerialName(value = "Diana") @Required val diana: ChampionObj,

    @SerialName(value = "Draven") @Required val draven: ChampionObj,

    @SerialName(value = "DrMundo") @Required val drMundo: ChampionObj,

    @SerialName(value = "Ekko") @Required val ekko: ChampionObj,

    @SerialName(value = "Elise") @Required val elise: ChampionObj,

    @SerialName(value = "Evelynn") @Required val evelynn: ChampionObj,

    @SerialName(value = "Ezreal") @Required val ezreal: ChampionObj,

    @SerialName(value = "Fiddlesticks") @Required val fiddlesticks: ChampionObj,

    @SerialName(value = "Fiora") @Required val fiora: ChampionObj,

    @SerialName(value = "Fizz") @Required val fizz: ChampionObj,

    @SerialName(value = "Galio") @Required val galio: ChampionObj,

    @SerialName(value = "Gangplank") @Required val gangplank: ChampionObj,

    @SerialName(value = "Garen") @Required val garen: ChampionObj,

    @SerialName(value = "Gnar") @Required val gnar: ChampionObj,

    @SerialName(value = "Gragas") @Required val gragas: ChampionObj,

    @SerialName(value = "Graves") @Required val graves: ChampionObj,

    @SerialName(value = "Gwen") @Required val gwen: ChampionObj,

    @SerialName(value = "Hecarim") @Required val hecarim: ChampionObj,

    @SerialName(value = "Heimerdinger") @Required val heimerdinger: ChampionObj,

    @SerialName(value = "Illaoi") @Required val illaoi: ChampionObj,

    @SerialName(value = "Irelia") @Required val irelia: ChampionObj,

    @SerialName(value = "Ivern") @Required val ivern: ChampionObj,

    @SerialName(value = "Janna") @Required val janna: ChampionObj,

    @SerialName(value = "JarvanIV") @Required val jarvanIV: ChampionObj,

    @SerialName(value = "Jax") @Required val jax: ChampionObj,

    @SerialName(value = "Jayce") @Required val jayce: ChampionObj,

    @SerialName(value = "Jhin") @Required val jhin: ChampionObj,

    @SerialName(value = "Jinx") @Required val jinx: ChampionObj,

    @SerialName(value = "Kaisa") @Required val kaisa: ChampionObj,

    @SerialName(value = "Kalista") @Required val kalista: ChampionObj,

    @SerialName(value = "Karma") @Required val karma: ChampionObj,

    @SerialName(value = "Karthus") @Required val karthus: ChampionObj,

    @SerialName(value = "Kassadin") @Required val kassadin: ChampionObj,

    @SerialName(value = "Katarina") @Required val katarina: ChampionObj,

    @SerialName(value = "Kayle") @Required val kayle: ChampionObj,

    @SerialName(value = "Kayn") @Required val kayn: ChampionObj,

    @SerialName(value = "Kennen") @Required val kennen: ChampionObj,

    @SerialName(value = "Khazix") @Required val khazix: ChampionObj,

    @SerialName(value = "Kindred") @Required val kindred: ChampionObj,

    @SerialName(value = "Kled") @Required val kled: ChampionObj,

    @SerialName(value = "KogMaw") @Required val kogMaw: ChampionObj,

    @SerialName(value = "KSante") @Required val ksante: ChampionObj,

    @SerialName(value = "Leblanc") @Required val leblanc: ChampionObj,

    @SerialName(value = "LeeSin") @Required val leeSin: ChampionObj,

    @SerialName(value = "Leona") @Required val leona: ChampionObj,

    @SerialName(value = "Lillia") @Required val lillia: ChampionObj,

    @SerialName(value = "Lissandra") @Required val lissandra: ChampionObj,

    @SerialName(value = "Lucian") @Required val lucian: ChampionObj,

    @SerialName(value = "Lulu") @Required val lulu: ChampionObj,

    @SerialName(value = "Lux") @Required val lux: ChampionObj,

    @SerialName(value = "Malphite") @Required val malphite: ChampionObj,

    @SerialName(value = "Malzahar") @Required val malzahar: ChampionObj,

    @SerialName(value = "Maokai") @Required val maokai: ChampionObj,

    @SerialName(value = "MasterYi") @Required val masterYi: ChampionObj,

    @SerialName(value = "Milio") @Required val milio: ChampionObj,

    @SerialName(value = "MissFortune") @Required val missFortune: ChampionObj,

    @SerialName(value = "MonkeyKing") @Required val monkeyKing: ChampionObj,

    @SerialName(value = "Mordekaiser") @Required val mordekaiser: ChampionObj,

    @SerialName(value = "Morgana") @Required val morgana: ChampionObj,

    @SerialName(value = "Naafiri") @Required val naafiri: ChampionObj,

    @SerialName(value = "Nami") @Required val nami: ChampionObj,

    @SerialName(value = "Nasus") @Required val nasus: ChampionObj,

    @SerialName(value = "Nautilus") @Required val nautilus: ChampionObj,

    @SerialName(value = "Neeko") @Required val neeko: ChampionObj,

    @SerialName(value = "Nidalee") @Required val nidalee: ChampionObj,

    @SerialName(value = "Nilah") @Required val nilah: ChampionObj,

    @SerialName(value = "Nocturne") @Required val nocturne: ChampionObj,

    @SerialName(value = "Nunu") @Required val nunu: ChampionObj,

    @SerialName(value = "Olaf") @Required val olaf: ChampionObj,

    @SerialName(value = "Orianna") @Required val orianna: ChampionObj,

    @SerialName(value = "Ornn") @Required val ornn: ChampionObj,

    @SerialName(value = "Pantheon") @Required val pantheon: ChampionObj,

    @SerialName(value = "Poppy") @Required val poppy: ChampionObj,

    @SerialName(value = "Pyke") @Required val pyke: ChampionObj,

    @SerialName(value = "Qiyana") @Required val qiyana: ChampionObj,

    @SerialName(value = "Quinn") @Required val quinn: ChampionObj,

    @SerialName(value = "Rakan") @Required val rakan: ChampionObj,

    @SerialName(value = "Rammus") @Required val rammus: ChampionObj,

    @SerialName(value = "RekSai") @Required val rekSai: ChampionObj,

    @SerialName(value = "Rell") @Required val rell: ChampionObj,

    @SerialName(value = "Renata") @Required val renata: ChampionObj,

    @SerialName(value = "Renekton") @Required val renekton: ChampionObj,

    @SerialName(value = "Rengar") @Required val rengar: ChampionObj,

    @SerialName(value = "Riven") @Required val riven: ChampionObj,

    @SerialName(value = "Rumble") @Required val rumble: ChampionObj,

    @SerialName(value = "Ryze") @Required val ryze: ChampionObj,

    @SerialName(value = "Samira") @Required val samira: ChampionObj,

    @SerialName(value = "Sejuani") @Required val sejuani: ChampionObj,

    @SerialName(value = "Senna") @Required val senna: ChampionObj,

    @SerialName(value = "Seraphine") @Required val seraphine: ChampionObj,

    @SerialName(value = "Sett") @Required val sett: ChampionObj,

    @SerialName(value = "Shaco") @Required val shaco: ChampionObj,

    @SerialName(value = "Shen") @Required val shen: ChampionObj,

    @SerialName(value = "Shyvana") @Required val shyvana: ChampionObj,

    @SerialName(value = "Singed") @Required val singed: ChampionObj,

    @SerialName(value = "Sion") @Required val sion: ChampionObj,

    @SerialName(value = "Sivir") @Required val sivir: ChampionObj,

    @SerialName(value = "Skarner") @Required val skarner: ChampionObj,

    @SerialName(value = "Sona") @Required val sona: ChampionObj,

    @SerialName(value = "Soraka") @Required val soraka: ChampionObj,

    @SerialName(value = "Swain") @Required val swain: ChampionObj,

    @SerialName(value = "Sylas") @Required val sylas: ChampionObj,

    @SerialName(value = "Syndra") @Required val syndra: ChampionObj,

    @SerialName(value = "TahmKench") @Required val tahmKench: ChampionObj,

    @SerialName(value = "Taliyah") @Required val taliyah: ChampionObj,

    @SerialName(value = "Talon") @Required val talon: ChampionObj,

    @SerialName(value = "Taric") @Required val taric: ChampionObj,

    @SerialName(value = "Teemo") @Required val teemo: ChampionObj,

    @SerialName(value = "Thresh") @Required val thresh: ChampionObj,

    @SerialName(value = "Tristana") @Required val tristana: ChampionObj,

    @SerialName(value = "Trundle") @Required val trundle: ChampionObj,

    @SerialName(value = "Tryndamere") @Required val tryndamere: ChampionObj,

    @SerialName(value = "TwistedFate") @Required val twistedFate: ChampionObj,

    @SerialName(value = "Twitch") @Required val twitch: ChampionObj,

    @SerialName(value = "Udyr") @Required val udyr: ChampionObj,

    @SerialName(value = "Urgot") @Required val urgot: ChampionObj,

    @SerialName(value = "Varus") @Required val varus: ChampionObj,

    @SerialName(value = "Vayne") @Required val vayne: ChampionObj,

    @SerialName(value = "Veigar") @Required val veigar: ChampionObj,

    @SerialName(value = "Velkoz") @Required val velkoz: ChampionObj,

    @SerialName(value = "Vex") @Required val vex: ChampionObj,

    @SerialName(value = "Vi") @Required val vi: ChampionObj,

    @SerialName(value = "Viego") @Required val viego: ChampionObj,

    @SerialName(value = "Viktor") @Required val viktor: ChampionObj,

    @SerialName(value = "Vladimir") @Required val vladimir: ChampionObj,

    @SerialName(value = "Volibear") @Required val volibear: ChampionObj,

    @SerialName(value = "Warwick") @Required val warwick: ChampionObj,

    @SerialName(value = "Xayah") @Required val xayah: ChampionObj,

    @SerialName(value = "Xerath") @Required val xerath: ChampionObj,

    @SerialName(value = "XinZhao") @Required val xinZhao: ChampionObj,

    @SerialName(value = "Yasuo") @Required val yasuo: ChampionObj,

    @SerialName(value = "Yone") @Required val yone: ChampionObj,

    @SerialName(value = "Yorick") @Required val yorick: ChampionObj,

    @SerialName(value = "Yuumi") @Required val yuumi: ChampionObj,

    @SerialName(value = "Zac") @Required val zac: ChampionObj,

    @SerialName(value = "Zed") @Required val zed: ChampionObj,

    @SerialName(value = "Zeri") @Required val zeri: ChampionObj,

    @SerialName(value = "Ziggs") @Required val ziggs: ChampionObj,

    @SerialName(value = "Zilean") @Required val zilean: ChampionObj,

    @SerialName(value = "Zoe") @Required val zoe: ChampionObj,

    @SerialName(value = "Zyra") @Required val zyra: ChampionObj

)

