/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.loldictionarykmp.models

import kotlinx.serialization.*

/**
 * 
 *
 * @param version 
 * @param id 
 * @param key 
 * @param name 
 * @param title 
 * @param blurb 
 * @param info 
 * @param image 
 * @param tags 
 * @param partype 
 * @param stats 
 */
@Serializable

data class ChampionObj (

    @SerialName(value = "version") @Required val version: kotlin.String,

    @SerialName(value = "id") @Required val id: kotlin.String,

    @SerialName(value = "key") @Required val key: kotlin.String,

    @SerialName(value = "name") @Required val name: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "blurb") @Required val blurb: kotlin.String,

    @SerialName(value = "info") @Required val info: InfoObj,

    @SerialName(value = "image") @Required val image: ImageObj,

    @SerialName(value = "tags") @Required val tags: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "partype") @Required val partype: kotlin.String,

    @SerialName(value = "stats") @Required val stats: StatsObj

)

