/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.loldictionarykmp.models


import kotlinx.serialization.*

/**
 * 
 *
 * @param full 
 * @param sprite 
 * @param group 
 * @param x 
 * @param y 
 * @param w 
 * @param h 
 */
@Serializable

data class ImageObj (

    @SerialName(value = "full") @Required val full: kotlin.String,

    @SerialName(value = "sprite") @Required val sprite: kotlin.String,

    @SerialName(value = "group") @Required val group: kotlin.String,

    @SerialName(value = "x") @Required val x: kotlin.Double,

    @SerialName(value = "y") @Required val y: kotlin.Double,

    @SerialName(value = "w") @Required val w: kotlin.Double,

    @SerialName(value = "h") @Required val h: kotlin.Double

)

