/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.loldictionarykmp.models


import kotlinx.serialization.*

/**
 * 
 *
 * @param attack 
 * @param defense 
 * @param magic 
 * @param difficulty 
 */
@Serializable

data class InfoObj (

    @SerialName(value = "attack") @Required val attack: kotlin.Double,

    @SerialName(value = "defense") @Required val defense: kotlin.Double,

    @SerialName(value = "magic") @Required val magic: kotlin.Double,

    @SerialName(value = "difficulty") @Required val difficulty: kotlin.Double

)

