/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.loldictionarykmp.models


import kotlinx.serialization.*

/**
 * 
 *
 * @param label 
 * @param effect 
 */
@Serializable

data class LevelTipObj (

    @SerialName(value = "label") @Required val label: kotlin.collections.List<kotlin.String>,

    @SerialName(value = "effect") @Required val effect: kotlin.collections.List<kotlin.String>

)

