/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.loldictionarykmp.models


import kotlinx.serialization.*

/**
 * 
 *
 * @param hp 
 * @param hpperlevel 
 * @param mp 
 * @param mpperlevel 
 * @param movespeed 
 * @param armor 
 * @param armorperlevel 
 * @param spellblock 
 * @param spellblockperlevel 
 * @param attackrange 
 * @param hpregen 
 * @param hpregenperlevel 
 * @param mpregen 
 * @param mpregenperlevel 
 * @param crit 
 * @param critperlevel 
 * @param attackdamage 
 * @param attackdamageperlevel 
 * @param attackspeedperlevel 
 * @param attackspeed 
 */
@Serializable

data class StatsObj (

    @SerialName(value = "hp") @Required val hp: kotlin.Double,

    @SerialName(value = "hpperlevel") @Required val hpperlevel: kotlin.Double,

    @SerialName(value = "mp") @Required val mp: kotlin.Double,

    @SerialName(value = "mpperlevel") @Required val mpperlevel: kotlin.Double,

    @SerialName(value = "movespeed") @Required val movespeed: kotlin.Double,

    @SerialName(value = "armor") @Required val armor: kotlin.Double,

    @SerialName(value = "armorperlevel") @Required val armorperlevel: kotlin.Double,

    @SerialName(value = "spellblock") @Required val spellblock: kotlin.Double,

    @SerialName(value = "spellblockperlevel") @Required val spellblockperlevel: kotlin.Double,

    @SerialName(value = "attackrange") @Required val attackrange: kotlin.Double,

    @SerialName(value = "hpregen") @Required val hpregen: kotlin.Double,

    @SerialName(value = "hpregenperlevel") @Required val hpregenperlevel: kotlin.Double,

    @SerialName(value = "mpregen") @Required val mpregen: kotlin.Double,

    @SerialName(value = "mpregenperlevel") @Required val mpregenperlevel: kotlin.Double,

    @SerialName(value = "crit") @Required val crit: kotlin.Double,

    @SerialName(value = "critperlevel") @Required val critperlevel: kotlin.Double,

    @SerialName(value = "attackdamage") @Required val attackdamage: kotlin.Double,

    @SerialName(value = "attackdamageperlevel") @Required val attackdamageperlevel: kotlin.Double,

    @SerialName(value = "attackspeedperlevel") @Required val attackspeedperlevel: kotlin.Double,

    @SerialName(value = "attackspeed") @Required val attackspeed: kotlin.Double

)

